-- ============================================================
-- Migration 003: Create Dimension Table (Establishments)
-- ============================================================
-- dim_estabelecimentos is the clean, relational representation
-- of hospitality establishments in Florianopolis.
--
-- Data flows: raw_crawled_data -> transform pipeline -> dim_estabelecimentos
--
-- PostGIS: The 'location' column stores WGS84 coordinates as
-- geography(Point, 4326), enabling spatial queries like
-- ST_DWithin for proximity search.
-- ============================================================

-- Enum for establishment types
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'establishment_type') THEN
        CREATE TYPE establishment_type AS ENUM (
            'hotel', 'hostel', 'pousada', 'guest_house',
            'restaurant', 'cafe', 'bar', 'pub', 'bakery', 'other'
        );
    END IF;
END$$;

CREATE TABLE IF NOT EXISTS public.dim_estabelecimentos (
    id                      uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    
    -- Identification
    nome                    text NOT NULL,
    nome_original           text,                    -- Name as received from source (pre-cleaning)
    
    -- Classification
    tipo                    establishment_type NOT NULL,
    subtipo                 text,                    -- Fine-grained subtype from LLM (e.g., 'fine_dining')
    cnae_codigo             text,                    -- CNAE subclass (e.g., '5510-8/01')
    
    -- Location
    endereco                text,
    bairro                  text,
    location                extensions.geography(Point, 4326),  -- PostGIS: lat/lon as geography
    
    -- Contact
    telefone                text,
    website                 text,
    horario_funcionamento   text,
    
    -- Reputation (from Google/Outscraper)
    rating_google           numeric(2,1),
    total_reviews           integer,
    
    -- Rich metadata
    cuisine                 text[],                  -- Array: {'italian', 'seafood', 'brazilian'}
    tags_llm                jsonb DEFAULT '{}'::jsonb,  -- LLM-generated tags and classifications
    source_refs             jsonb DEFAULT '{}'::jsonb,  -- Cross-references: {osm_id, place_id, cadastur}
    
    -- Status
    ativo                   boolean NOT NULL DEFAULT true,
    
    -- Audit
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    
    -- Constraints
    CONSTRAINT valid_rating CHECK (rating_google IS NULL OR (rating_google >= 0 AND rating_google <= 5)),
    CONSTRAINT valid_reviews CHECK (total_reviews IS NULL OR total_reviews >= 0)
);

-- Add descriptive comments
COMMENT ON TABLE public.dim_estabelecimentos IS
    'Clean dimension table of hospitality establishments in Florianopolis. Data validated through Pydantic + LLM classification.';
COMMENT ON COLUMN public.dim_estabelecimentos.location IS
    'PostGIS geography point (WGS84 SRID 4326). Enables spatial queries: ST_DWithin, ST_Distance.';
COMMENT ON COLUMN public.dim_estabelecimentos.tags_llm IS
    'JSON tags generated by the LLM classifier: {pet_friendly: true, wifi: true, ocean_view: true}';

-- Auto-update updated_at on row modification
CREATE OR REPLACE FUNCTION update_dim_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_dim_estabelecimentos_updated_at
    BEFORE UPDATE ON public.dim_estabelecimentos
    FOR EACH ROW
    EXECUTE FUNCTION update_dim_updated_at();
